name: SCCore
authors: [Anml]
version: 1.0
main: net.anmlmc.SCCore.Main
depend: [Essentials]
commands:
  shout:
    aliases: [s]
  rank:
    default: false
  perms:
    default: false
  arena:
    default: false
  duel:
  spectate:
  combattime:
    aliases: [ct]
